name: pages

on:
  push:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
        timeout-minutes: 5

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: corepack enable

      - run: yarn install --immutable

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4